version: "3.9"
services: 
  apache-flask:
    container_name: Apache-Flask
    build: ./REST Train Filtering/
    links:
      - mysql
    ports:
      - 8888:80
    networks:
      net: {}

  mysql:
    container_name: MySQL
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: secf
      MYSQL_USER: secf
    volumes:
      - ./REST Train Filtering/db:/docker-entrypoint-initdb.d
    networks:
      net: {}

  adminer:
    container_name: Adminer
    image: adminer
    ports:
      - 8080:8080

networks:
  net: