version: "3.9"
services: 
  apache-flask:
    container_name: Apache-Flask
    build: ./REST Train Filtering/
    links:
      - db
    ports:
      - 8888:80
    networks:
      net: {}

  db:
    image: mysql:5.7

    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: secf
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    volumes:
      - ./REST Train Filtering/db:/var/lib/mysql
    networks:
      net: {}

  phpmyadmin:
      depends_on:
        - db
      image: phpmyadmin/phpmyadmin
      restart: always
      ports:
        - 8088:80
      environment:
        PMA_HOST: db
        MYSQL_ROOT_PASSWORD: root
      networks:
        net: {}

networks:
  net: